services:
    log.listener:
        class: Zuni\LogBundle\EventListener\LogListener
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: preRemove }
            - { name: doctrine.event_listener, event: postFlush }